INSERT INTO webhook_registrations (
    registration_id, 
    callback_url, 
    static_headers, 
    auth_type, 
    auth_url, 
    token_expiry, 
    signature_algorithm, 
    signature_secretkey, 
    signature_headername, 
    auth_client_id, 
    auth_client_secret, 
    param_name_client_id, 
    param_name_client_secret, 
    content_type, 
    auth_grant_type, 
    jwt_field_name, 
    claims, 
    param_name_token, 
    grant_type, 
    param_name_grant_type, 
    registration_datetime, 
    client_id, 
    email_id
) VALUES (
    'reg12345', 
    'https://example.com/callback', 
    '{"header1": "value1", "header2": "value2"}', 
    'OAuth2', 
    'https://auth.example.com', 
    3600, 
    'HS256', 
    'mySecretKey', 
    'Authorization', 
    'myClientId', 
    'myClientSecret', 
    'client_id', 
    'client_secret', 
    'application/json', 
    'client_credentials', 
    'jwt_field', 
    '{"claim1": "value1", "claim2": "value2"}', 
    'access_token', 
    'authorization_code', 
    'grant_type', 
    '2024-09-17 12:34:56', 
    'myClientId', 
    'example@example.com'
);
