CREATE TABLE webhook_registrations (
    registration_id VARCHAR(255) NOT NULL,
    callback_url VARCHAR(255),
    static_headers JSON,
    auth_type VARCHAR(255),
    auth_url VARCHAR(255),
    token_expiry INT,
    signature_algorithm VARCHAR(255),
    signature_secretkey VARCHAR(255),
    signature_headername VARCHAR(255),
    auth_client_id VARCHAR(255),
    auth_client_secret VARCHAR(255),
    param_name_client_id VARCHAR(255),
    param_name_client_secret VARCHAR(255),
    content_type VARCHAR(255),
    auth_grant_type VARCHAR(255),
    jwt_field_name VARCHAR(255),
    claims JSON,
    param_name_token VARCHAR(255),
    grant_type VARCHAR(255),
    param_name_grant_type VARCHAR(255),
    registration_datetime TIMESTAMP,
    client_id VARCHAR(255) NOT NULL,
    email_id VARCHAR(255),
    PRIMARY KEY (registration_id)
);
